### ISSUE TITLE
TYPE is missing from nodes

### ISSUE THREAD

**Issue by aaryani** [researchgraph/ANDS#2]
nodes.csv requires the column `type` that identifies the type of the node. The expected values are
- dataset
- publication
- researcher
- grant
- auxiliary 

"auxiliary" type is used for anything rather than {publication, dataset, grant and researcher}.

you can also add any custom columns to the CSV such as 'ands_class' or 'ands_type' that includes any information from ANDS registry. For example, for an activity record:
- node.type = auxiliary
- node.ands_class = 'service'
- node.ands_type = 'transform'

Note: All custom fields should start with 'ands_...'

**Comment by minhd** [comment]
Fixed with c1ff3f27fa235d6886ce7915afb2422e8bfcfbcc
